name: CI/CD Workflow for Branch-based Deployment

on:
  push:
    branches:
      - project-a  # 當 project-a 分支有更新時觸發
      - project-b  # 當 project-b 分支有更新時觸發

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: v18.16.0

    - name: Install pnpm
      run: |
        corepack enable
        pnpm --version

    - name: Install dependencies
      run: pnpm install

    - name: Determine Project
      id: project
      run: echo "PROJECT=${{ github.ref_name }}" >> $GITHUB_ENV

    - name: Build the project
      if: ${{ github.ref_name == 'project-a' || github.ref_name == 'project-b' }}
      run: pnpm run build
      working-directory: apps/${{ github.ref_name }}

    - name: Deploy ${{ github.ref_name }} to GitHub Pages
      if: ${{ github.ref_name == 'project-a' || github.ref_name == 'project-b' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: apps/${{ github.ref_name }}/dist
        publish_branch: gh-pages
        destination_dir: ${{ github.ref_name }}  # 指定不同子目錄
