name: CI/CD Workflow for GitHub Pages

on:
  push:
    branches:
      - main  # 監控 main 分支的變更

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18  # 確保版本與專案相符
        cache: pnpm  # 開啟 pnpm 緩存

    # 安裝 pnpm 並加入 PATH
    - name: Install pnpm
      run: |
        npm install -g pnpm
        pnpm --version  # 驗證 pnpm 是否正確安裝

    - name: Install dependencies
      run: pnpm install

    - name: Build project-a
      working-directory: apps/project-a
      run: pnpm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: apps/project-a/dist  # Vite 預設輸出目錄
